[package]
name = "meilisearch-tokenizer"
version = "0.2.5"
license = "MIT"
authors = ["Many <many@meilisearch.com>"]
edition = "2018"

[dependencies]
character_converter = "1.0.0"
cow-utils = "0.1"
deunicode = "1.1.1"
fst = "0.4"
jieba-rs = "0.6"
once_cell = "1.5.2"
slice-group-by = "0.2.6"
unicode-segmentation = "1.6.0"
whatlang = "0.12.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
